// qrCore is a from-scratch QR encoder, so the only test worth writing is one that
// checks it against a reference implementation — not against itself.
//
// `tests/fixtures/qr-golden.json` is generated by **qrencode** (libqrencode, the
// same binary `utils/prepare-youtube.sh` shells out to), in byte mode, with no quiet
// zone. Two kinds of golden data:
//
//   matrices — whole module grids for short, readable payloads. Debuggable by eye:
//              a failure prints the row that drifted.
//   digests  — sha256 of the grid for ALL 160 (version × ecc) combinations, twice
//              over: once at exactly full capacity (no padding, every block packed)
//              and once below it (terminator + 0xEC/0x11 pad codewords in play).
//
// Between them they pin every part of the pipeline a unit test cannot see the shape
// of: version selection, the ECC block split, Reed-Solomon, interleaving, module
// placement, and the format and version information. If a single ECC-table entry
// were off by one, the digest for that one (version, level) would move and nothing
// else would.
//
// **The mask is pinned, not compared.** Each case records the mask qrencode chose,
// decoded from the reference symbol's own format bits, and we encode with that mask.
// Mask selection is a heuristic — the spec's penalty rules admit more than one honest
// reading, and conforming encoders differ on maybe 7% of payloads — but the chosen
// mask is written into the symbol, so a decoder reads whichever we picked. What must
// match is everything downstream of that choice, and it does, module for module.
// `penaltyScore` and the auto-selection are tested separately, below, against the
// spec's own rules.
//
// The rest of the file is the discipline the other cores keep: totality. Junk in,
// null or a clamped default out, never a throw.
import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import {
	alignmentPatternPositions,
	byteCapacity,
	chooseVersion,
	encodeQr,
	numDataCodewords,
	penaltyScore,
	qrExtent,
	qrPath,
	toUtf8Bytes,
	versionBits,
	type Ecc,
	type QrMatrix,
} from '../src/lib/utils/qrCore';
import golden from './fixtures/qr-golden.json';

/** The matrix as qrencode's ASCII art renders it: one row per line, '1' = dark. */
function rowsOf(matrix: QrMatrix): string[] {
	return matrix.modules.map((row) => row.map((dark) => (dark ? '1' : '0')).join(''));
}

function digestOf(matrix: QrMatrix): string {
	return createHash('sha256').update(rowsOf(matrix).join('\n')).digest('hex');
}

describe('qrCore — against qrencode', () => {
	it.each(golden.matrices)('matches the reference grid: v$version-$ecc $text', (expected) => {
		const matrix = encodeQr(expected.text, { ecc: expected.ecc as Ecc, mask: expected.mask });
		expect(matrix).not.toBeNull();
		expect(matrix!.version).toBe(expected.version);
		expect(matrix!.size).toBe(expected.rows.length);
		// Row by row, so a failure names the row rather than dumping the whole symbol.
		expect(rowsOf(matrix!)).toEqual(expected.rows);
	});

	// 320 cases: every version, every level, packed full and padded short.
	it.each(golden.digests)(
		'matches the reference digest: v$version-$ecc $char×$length',
		(expected) => {
			const matrix = encodeQr(expected.char.repeat(expected.length), {
				ecc: expected.ecc as Ecc,
				// The fixture pinned qrencode to this version (`-v`); a short payload
				// would otherwise pick a smaller one. Same instruction, same symbol.
				minVersion: expected.version,
				mask: expected.mask,
			});
			expect(matrix).not.toBeNull();
			expect(matrix!.version).toBe(expected.version);
			expect(digestOf(matrix!)).toBe(expected.sha256);
		},
	);

	it('picks the same version qrencode does, left to itself', () => {
		// The fixture pinned the version; version SELECTION is what this checks. The
		// `A` cases sit at exactly full capacity, so the version below must not fit.
		for (const g of golden.matrices) {
			expect(encodeQr(g.text, { ecc: g.ecc as Ecc })!.version).toBe(g.version);
		}
		for (const g of golden.digests) {
			if (g.char !== 'A') continue;
			expect(encodeQr('A'.repeat(g.length), { ecc: g.ecc as Ecc })!.version).toBe(g.version);
		}
	});

	it('agrees with qrencode on the capacity of every version and level', () => {
		// The `A` rows of the digest table were generated at exactly full capacity —
		// qrencode accepted them at that version, so this IS the published table.
		for (const entry of golden.digests) {
			if (entry.char !== 'A') continue;
			expect(byteCapacity(entry.version, entry.ecc as Ecc)).toBe(entry.length);
		}
	});

	it('writes a format string a decoder can read back', () => {
		// The reference mask was recovered from the golden symbol's format bits using
		// this exact placement, so reading our own back closes the loop: whatever mask
		// auto-selection lands on, the symbol announces it.
		const positions: Array<[number, number]> = [
			...Array.from({ length: 6 }, (_, i) => [8, i] as [number, number]),
			[8, 7],
			[8, 8],
			[7, 8],
			...Array.from({ length: 6 }, (_, i) => [14 - (i + 9), 8] as [number, number]),
		];
		for (const ecc of ['L', 'M', 'Q', 'H'] as Ecc[]) {
			const matrix = encodeQr('https://geekpresent.dev', { ecc })!;
			let bits = 0;
			positions.forEach(([x, y], i) => {
				if (matrix.modules[y][x]) bits |= 1 << i;
			});
			const data = ((bits ^ 0x5412) >>> 10) & 0b11111;
			expect(data & 0b111).toBe(matrix.mask);
			expect(({ 1: 'L', 0: 'M', 3: 'Q', 2: 'H' } as const)[(data >>> 3) as 0 | 1 | 2 | 3]).toBe(ecc);
		}
	});
});

describe('qrCore — structure', () => {
	it('sizes the symbol at 4v + 17 modules', () => {
		for (const [text, version] of [
			['HI', 1],
			['https://geekpresent.dev', 2],
			['A'.repeat(300), 13],
		] as const) {
			const matrix = encodeQr(text)!;
			expect(matrix.version).toBe(version);
			expect(matrix.size).toBe(version * 4 + 17);
		}
	});

	it('places the dark module, which every symbol carries at (8, size-8)', () => {
		for (const ecc of ['L', 'M', 'Q', 'H'] as Ecc[]) {
			const matrix = encodeQr('geekpresent', { ecc })!;
			expect(matrix.modules[matrix.size - 8][8]).toBe(true);
		}
	});

	it('draws the timing patterns as an alternating spine', () => {
		const { modules, size } = encodeQr('timing')!;
		for (let i = 8; i < size - 8; i++) {
			expect(modules[6][i]).toBe(i % 2 === 0);
			expect(modules[i][6]).toBe(i % 2 === 0);
		}
	});

	it('spaces the alignment patterns as the spec tabulates them', () => {
		expect(alignmentPatternPositions(1)).toEqual([]);
		expect(alignmentPatternPositions(2)).toEqual([6, 18]);
		expect(alignmentPatternPositions(7)).toEqual([6, 22, 38]);
		expect(alignmentPatternPositions(14)).toEqual([6, 26, 46, 66]);
		// Version 32 is the one row the derived step gets wrong (28, not 26).
		expect(alignmentPatternPositions(32)).toEqual([6, 34, 60, 86, 112, 138]);
		expect(alignmentPatternPositions(40)).toEqual([6, 30, 58, 86, 114, 142, 170]);
	});

	it('encodes the version information string of version 7', () => {
		// The spec's own worked example: 000111 110010010100.
		expect(versionBits(7)).toBe(0b000111110010010100);
	});

	it('honours a pinned mask, and records whichever mask was used', () => {
		for (let mask = 0; mask < 8; mask++) {
			expect(encodeQr('mask', { mask })!.mask).toBe(mask);
		}
		// Auto-selection lands on one of the eight and says so.
		const auto = encodeQr('mask')!;
		expect(auto.mask).toBeGreaterThanOrEqual(0);
		expect(auto.mask).toBeLessThan(8);
	});

	it('a pinned mask changes the modules but not the version', () => {
		const a = encodeQr('https://geekpresent.dev', { mask: 0 })!;
		const b = encodeQr('https://geekpresent.dev', { mask: 5 })!;
		expect(a.version).toBe(b.version);
		expect(rowsOf(a)).not.toEqual(rowsOf(b));
	});

	it('applies each of the eight mask patterns exactly as the spec defines them', () => {
		// The golden fixture only ever exercises the masks qrencode happened to choose
		// (it never picks 5), so the eight formulas are pinned here instead, against an
		// independent transcription of Table 10 — rows are `i`, columns are `j`.
		const SPEC: ReadonlyArray<(i: number, j: number) => boolean> = [
			(i, j) => (i + j) % 2 === 0,
			(i) => i % 2 === 0,
			(_i, j) => j % 3 === 0,
			(i, j) => (i + j) % 3 === 0,
			(i, j) => (Math.floor(i / 2) + Math.floor(j / 3)) % 2 === 0,
			(i, j) => ((i * j) % 2) + ((i * j) % 3) === 0,
			(i, j) => (((i * j) % 2) + ((i * j) % 3)) % 2 === 0,
			(i, j) => (((i + j) % 2) + ((i * j) % 3)) % 2 === 0,
		];

		// A version-10 symbol (57 modules) whose alignment centres sit at 6/28/50, each
		// spanning ±2. The window below clears them, both timing lines, the format and
		// version blocks, and every corner — so it is pure data region, where the mask
		// is the ONLY thing that can differ between two symbols of the same text.
		const text = 'A'.repeat(200);
		expect(alignmentPatternPositions(10)).toEqual([6, 28, 50]);
		const base = encodeQr(text, { minVersion: 10, maxVersion: 10, mask: 0 })!;
		expect(base.version).toBe(10);

		for (let mask = 1; mask < 8; mask++) {
			const other = encodeQr(text, { minVersion: 10, maxVersion: 10, mask })!;
			for (let y = 32; y <= 44; y++) {
				for (let x = 32; x <= 44; x++) {
					// Two symbols of the same data differ at exactly the modules where their
					// two mask patterns disagree.
					const flipped = base.modules[y][x] !== other.modules[y][x];
					expect(flipped).toBe(SPEC[0](y, x) !== SPEC[mask](y, x));
				}
			}
		}
	});

	it('spends more of the budget on ECC as the level rises', () => {
		const data = (['L', 'M', 'Q', 'H'] as Ecc[]).map((ecc) => numDataCodewords(10, ecc));
		expect(data).toEqual([...data].sort((a, b) => b - a));
	});
});

describe('qrCore — mask penalty', () => {
	/** A grid from '#'/'.' art, so a rule can be shown rather than described. */
	const grid = (...rows: string[]) => rows.map((row) => [...row].map((c) => c === '#'));

	/** A checkerboard: no runs, no 2×2 blocks, no finder-alikes, and ~50% dark. */
	const checker = (size: number) =>
		Array.from({ length: size }, (_, y) =>
			Array.from({ length: size }, (_, x) => (x + y) % 2 === 0 ? '#' : '.').join(''),
		);

	// Rules 1, 2 and 4 are arithmetic nobody disputes, so the test recomputes them
	// here and subtracts, leaving rule 3 — the one with the interesting semantics —
	// measurable on its own.
	const linesOf = (g: boolean[][]) => [
		...g,
		...g[0].map((_, x) => g.map((row) => row[x])),
	];
	const rule1 = (g: boolean[][]) =>
		linesOf(g).reduce((sum, line) => {
			let s = 0;
			let run = 1;
			for (let i = 1; i < line.length; i++) {
				if (line[i] === line[i - 1]) run++;
				else run = 1;
				if (run === 5) s += 3;
				else if (run > 5) s += 1;
			}
			return sum + s;
		}, 0);
	const rule2 = (g: boolean[][]) => {
		let s = 0;
		for (let y = 0; y < g.length - 1; y++)
			for (let x = 0; x < g.length - 1; x++)
				if (g[y][x] === g[y][x + 1] && g[y][x] === g[y + 1][x] && g[y][x] === g[y + 1][x + 1]) s += 3;
		return s;
	};
	const rule4 = (g: boolean[][]) => {
		const dark = g.flat().filter(Boolean).length;
		const percent = Math.floor((100 * dark) / (g.length * g.length));
		return Math.floor(Math.abs(percent - 50) / 5) * 10;
	};
	/** What rule 3 alone contributed to the score. */
	const rule3 = (g: boolean[][]) => penaltyScore(g, g.length) - rule1(g) - rule2(g) - rule4(g);

	it('scores an all-light grid at exactly rule 1 + rule 2 + rule 4', () => {
		// 5×5 light: ten runs of 5 (3 each) = 30, sixteen 2×2 blocks (3 each) = 48,
		// and 0% dark — the furthest rule 4 can push, ten 5%-steps = 100.
		expect(penaltyScore(grid(...Array(5).fill('.....')), 5)).toBe(30 + 48 + 100);
		// 6×6: twelve runs of 6 (3 + 1 each) = 48, twenty-five blocks = 75, plus 100.
		expect(penaltyScore(grid(...Array(6).fill('......')), 6)).toBe(48 + 75 + 100);
		// All-dark is the mirror image: same runs, same blocks, 100% dark.
		expect(penaltyScore(grid(...Array(5).fill('#####')), 5)).toBe(30 + 48 + 100);
	});

	it('scores a checkerboard at zero — the mask every rule is happy with', () => {
		// No run reaches 5, no 2×2 is uniform, no ratio resembles a finder, and the
		// dark share rounds to 50%. This is the floor the penalty is aiming at.
		expect(penaltyScore(grid(...checker(6)), 6)).toBe(0);
		expect(penaltyScore(grid(...checker(11)), 11)).toBe(0);
	});

	it('rule 3: the finder signature costs 40, counted once per occurrence', () => {
		// Four light, then 1:1:3:1:1, then four light. Both margins qualify — the spec
		// says "preceded OR followed", so this is 40, not 80.
		const rows = ['....#.###.#....', ...checker(15).slice(1)];
		expect(rule3(grid(...rows))).toBe(40);

		// Break the centre run and the ratio is gone.
		const broken = ['....#.##..#....', ...checker(15).slice(1)];
		expect(rule3(grid(...broken))).toBe(0);
	});

	it('rule 3: the signature is a RATIO, so it counts at any scale', () => {
		// 2:2:6:2:2, with an eight-module light margin (4 × the unit). A scanner reads
		// ratios, not module counts, so this is as misleading as the 1:1:3:1:1 version.
		const rows = ['........##..######..##........', ...checker(30).slice(1)];
		expect(rule3(grid(...rows))).toBe(40);

		// A centre of five is not divisible by three: no ratio, no penalty.
		const off = ['........##..#####...##........', ...checker(30).slice(1)];
		expect(rule3(grid(...off))).toBe(0);
	});

	it('rule 3: the quiet zone beyond the edge counts as the light margin', () => {
		// Flush against the start of the line. There is nothing to its left inside the
		// symbol — but the quiet zone is light and four modules wide by definition.
		const flush = ['#.###.#........', ...checker(15).slice(1)];
		expect(rule3(grid(...flush))).toBe(40);
	});

	it('rule 3: three light modules are not four', () => {
		const rows = ['...#.###.#...', ...checker(13).slice(1)];
		expect(rule3(grid(...rows))).toBe(0);
	});

	it('auto-selection returns the lowest-scoring mask, ties going to the lowest index', () => {
		for (const text of ['HI', 'https://geekpresent.dev', 'The quick brown fox', 'A'.repeat(300)]) {
			const auto = encodeQr(text)!;
			const scores = Array.from({ length: 8 }, (_, mask) => {
				const m = encodeQr(text, { mask })!;
				return penaltyScore(m.modules, m.size);
			});
			const best = Math.min(...scores);
			expect(scores[auto.mask]).toBe(best);
			expect(auto.mask).toBe(scores.indexOf(best));
		}
	});
});

describe('qrCore — UTF-8', () => {
	it('encodes ASCII one byte per character', () => {
		expect(toUtf8Bytes('HI')).toEqual([0x48, 0x49]);
	});

	it('encodes the two-, three- and four-byte forms', () => {
		expect(toUtf8Bytes('é')).toEqual([0xc3, 0xa9]);
		expect(toUtf8Bytes('☕')).toEqual([0xe2, 0x98, 0x95]);
		expect(toUtf8Bytes('😀')).toEqual([0xf0, 0x9f, 0x98, 0x80]);
	});

	it('replaces a lone surrogate rather than emitting undecodable bytes', () => {
		// U+FFFD. A broken paste must not produce a symbol no scanner can read.
		expect(toUtf8Bytes('\ud800')).toEqual([0xef, 0xbf, 0xbd]);
		expect(toUtf8Bytes('\udc00')).toEqual([0xef, 0xbf, 0xbd]);
	});

	it('counts capacity in bytes, not characters', () => {
		// Version 1-L holds 17 bytes: 17 ASCII characters, or 8 emoji with a byte to spare.
		expect(encodeQr('A'.repeat(17), { ecc: 'L', maxVersion: 1 })).not.toBeNull();
		expect(encodeQr('A'.repeat(18), { ecc: 'L', maxVersion: 1 })).toBeNull();
		expect(encodeQr('😀'.repeat(4), { ecc: 'L', maxVersion: 1 })).not.toBeNull();
		expect(encodeQr('😀'.repeat(5), { ecc: 'L', maxVersion: 1 })).toBeNull();
	});
});

describe('qrCore — totality', () => {
	it('returns null for anything that is not encodable text', () => {
		for (const junk of ['', null, undefined, 42, {}, [], NaN]) {
			expect(encodeQr(junk as unknown)).toBeNull();
		}
	});

	it('returns null — never a throw — for a payload past the largest symbol', () => {
		expect(encodeQr('A'.repeat(2954), { ecc: 'L' })).toBeNull();
		expect(encodeQr('A'.repeat(2953), { ecc: 'L' })!.version).toBe(40);
		expect(encodeQr('A'.repeat(1274), { ecc: 'H' })).toBeNull();
	});

	it('falls back to M for an unknown ecc level, and accepts a lowercase one', () => {
		expect(encodeQr('x', { ecc: 'Z' as Ecc })!.ecc).toBe('M');
		expect(encodeQr('x', { ecc: undefined })!.ecc).toBe('M');
		expect(encodeQr('x', { ecc: 'h' as Ecc })!.ecc).toBe('H');
	});

	it('clamps a junk mask back to auto-selection instead of indexing off the end', () => {
		for (const mask of [-1, 8, 99, 1.5, NaN, Infinity, 'x' as unknown as number]) {
			const matrix = encodeQr('junk mask', { mask });
			expect(matrix).not.toBeNull();
			expect(matrix!.mask).toBeGreaterThanOrEqual(0);
			expect(matrix!.mask).toBeLessThan(8);
		}
	});

	it('clamps junk version bounds into 1..40', () => {
		expect(encodeQr('x', { minVersion: 0, maxVersion: 99 })!.version).toBe(1);
		expect(encodeQr('x', { minVersion: 5 })!.version).toBe(5);
		expect(encodeQr('x', { minVersion: NaN as number })!.version).toBe(1);
		// An inverted range collapses to the floor rather than producing no versions.
		expect(encodeQr('x', { minVersion: 9, maxVersion: 2 })!.version).toBe(9);
	});

	it('chooseVersion reports failure rather than guessing', () => {
		expect(chooseVersion(3000, 'L', 1, 40)).toBeNull();
		expect(chooseVersion(17, 'L', 1, 40)).toBe(1);
		expect(chooseVersion(18, 'L', 1, 40)).toBe(2);
	});
});

describe('qrCore — qrPath', () => {
	it('merges each horizontal run of dark modules into one rectangle', () => {
		// The top-left finder opens with seven dark modules in a row: one `h7`, not seven `h1`.
		const matrix = encodeQr('HI', { ecc: 'L' })!;
		expect(qrPath(matrix, 0)).toMatch(/^M0 0h7v1h-7z/);
	});

	it('offsets every module by the quiet zone, and extends the canvas to match', () => {
		const matrix = encodeQr('HI', { ecc: 'L' })!;
		expect(qrPath(matrix, 4)).toMatch(/^M4 4h7v1h-7z/);
		expect(qrExtent(matrix, 4)).toBe(21 + 8);
		expect(qrExtent(matrix, 0)).toBe(21);
	});

	it('emits nothing at all for a null matrix', () => {
		expect(qrPath(null)).toBe('');
		expect(qrExtent(null)).toBe(0);
	});

	it('clamps a junk quiet zone back to the spec default of four modules', () => {
		const matrix = encodeQr('HI', { ecc: 'L' })!;
		for (const quiet of [NaN, undefined, 'x' as unknown as number]) {
			expect(qrExtent(matrix, quiet as number)).toBe(21 + 8);
		}
		expect(qrExtent(matrix, -5)).toBe(21); // negative → 0, not a shrunken symbol
	});
});
