export const pages = [
    { path: "title.html",             title: "Title" },
    { path: "what-is-geekpresent.html", title: "What is GeekPresent?" },
    { path: "project-structure.html", title: "Project Structure" },
    { path: "title-page.html",        title: "Using TitlePage" },
    { path: "content-page.html",      title: "Using ContentPage" },
    { path: "navigation.html",        title: "Navigation" },
    { path: "components.html",        title: "Components" },
    { path: "box-component.html",     title: "Box Component" },
    { path: "block-component.html",   title: "Block Component" },
    { path: "highlight-component.html", title: "Highlight Component" },
    { path: "carousel-component.html", title: "Carousel Component" },
    { path: "datatable-component.html", title: "DataTable — Static Data" },
    { path: "datatable-tools.html",   title: "DataTable — Table Tools" },
    { path: "datatable-server.html",  title: "DataTable — Server-Side Data" },
    { path: "draw-component.html",    title: "Draw — Shapes & Arrows" },
    { path: "chart-bar.html",         title: "Chart — Grouped & Stacked Bars" },
    { path: "chart-line.html",        title: "Chart — Dual-Axis Line + Time" },
    { path: "chart-combo.html",       title: "Chart — Combo (Bars + Line)" },
    { path: "youtube-showcase.html",  title: "YouTube" },
    { path: "hint-component.html",    title: "Hint" },
    { path: "label-component.html",   title: "Label" },
    { path: "scrolldiv-component.html", title: "ScrollDiv" },
    { path: "code-component.html",    title: "Code" },
    { path: "javacode-component.html", title: "JavaCode" },
    { path: "codebox-component.html", title: "CodeBox" },
    { path: "speaker-notes.html",     title: "Speaker Notes" },
    { path: "thank-you.html",         title: "Thank You" },
];
