export const pages = [
    { path: "title.html",             title: "Title" },
    { path: "what-is-geekpresent.html", title: "What is GeekPresent?" },
    { path: "project-structure.html", title: "Project Structure" },
    { path: "title-page.html",        title: "Using TitlePage" },
    { path: "content-page.html",      title: "Using ContentPage" },
    { path: "content-header.html",    title: "The ContentPage Header" },
    { path: "navigation.html",        title: "Navigation" },
    { path: "components.html",        title: "Components" },
    { path: "box-component.html",     title: "Box Component" },
    { path: "block-component.html",   title: "Block Component" },
    { path: "highlight-component.html", title: "Highlight Component" },
    { path: "carousel-component.html", title: "Carousel Component" },
    { path: "steps-component.html",   title: "Steps & Fragment" },
    { path: "datatable-component.html", title: "DataTable — Static Data" },
    { path: "datatable-tools.html",   title: "DataTable — Table Tools" },
    { path: "datatable-server.html",  title: "DataTable — Server-Side Data" },
    { path: "draw-component.html",    title: "Draw — Shapes & Arrows" },
    { path: "connector-component.html", title: "Connector — Arrows by Name" },
    { path: "chart-bar.html",         title: "Chart — Grouped & Stacked Bars" },
    { path: "chart-line.html",        title: "Chart — Dual-Axis Line + Time" },
    { path: "chart-combo.html",       title: "Chart — Combo (Bars + Line)" },
    { path: "chart-scatter.html",     title: "Chart — Bubble Scatter" },
    { path: "chart-area.html",        title: "Chart — Stacked Area + Draw-In" },
    { path: "function-graph.html",    title: "Chart — Plotting y = f(x)" },
    { path: "datatable-chart.html",   title: "DataTable + Charts — One Dataset" },
    { path: "youtube-showcase.html",  title: "YouTube" },
    { path: "website-component.html", title: "WebSite — Embedded Site" },
    { path: "webpage-component.html", title: "WebPage — Full-Canvas Site" },
    { path: "video-component.html",   title: "Video — Player & Bookmarks" },
    { path: "videopage-component.html", title: "VideoPage — Full-Canvas Video" },
    { path: "hint-component.html",    title: "Hint" },
    { path: "callout-component.html", title: "Callout" },
    { path: "stat-component.html",    title: "Stat & StatGroup" },
    { path: "quote-component.html",   title: "Quote" },
    { path: "columns-component.html", title: "Columns & Column" },
    { path: "kbd-component.html",     title: "Kbd" },
    { path: "qrcode-component.html",  title: "QRCode" },
    { path: "label-component.html",   title: "Label" },
    { path: "scrolldiv-component.html", title: "ScrollDiv" },
    { path: "code-component.html",    title: "Code" },
    { path: "javacode-component.html", title: "JavaCode" },
    { path: "codebox-component.html", title: "CodeBox" },
    { path: "terminal-component.html", title: "Terminal" },
    { path: "speaker-notes.html",     title: "Speaker Notes" },
    { path: "thank-you.html",         title: "Thank You" },
];
